apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::351715870699:role/UdacityFlaskDeployCBKubectlRole
      username: build  
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::351715870699:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-174NLGGWJXG0J
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2021-08-30T15:45:55Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1287"
  uid: 0d905279-a7d3-4f66-b59b-d7c7e2d57940
